# Site settings
title: TopLap IL
description: "Home of the live coding community in Israel."
baseurl: "" # for test: remove string '/space-jekyll-template' to ''
url: "https://algorave-israel.github.io" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.github.io'

# User settings
username: "Home of the live coding community in Israel"
user_title: "TopLap IL"
email: mynah@earthtoabigail.com
twitter_username: EarthAbigail
github_username:  EarthToAbigail
linkedin_public_url: https://www.linkedin.com/in/mynah-marie # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
disqus_username: toplap-israel
profile_picture: /assets/img/home/logo-black-cropped.png

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: h
    - title: about
      url: /about
      key_trigger: a
    - title: blog
      url: /blog
      key_trigger: b
    - title: calendar
      url: /calendar
      key_trigger: c
  section_2:
    - title: github
      url: https://www.github.com/TOPLAP-Israel
      new_tab: true
      key_trigger: g
    - title: facebook
      url: https://www.facebook.com/groups/866355520434300/
      new_tab: true
      key_trigger: f
    - title: search
      url: ""
      key_trigger: s

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
